### ISSUE TITLE
IsIsomorphic #3 

### ISSUE THREAD

**Issue by eobr007** [thetensor-space/TameGenus#15] opened 2019-03-02 04:24 UTC
These groups were constructed as isomorphic, but TGIsIsom ... returns false.

PCGroup(\[ 14, -3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, -3, 3, 119042869, 44641424, 
29762211, 49601681, 9920431, 74407414, 24802488, 33068102, 1378066, 59528215, 
9921035, 3858181, 156315102, 52105052, 40515586, 5789496, 1286900, 857674, 
297851911, 138964917, 6640739, 8827105, 737919, 1225805, 327019, 268672958, 
67237150, 29852586, 2490328, 1932414, 93080, 153574, 449166069, 174522623, 
952625, 1542319, 137447, 68581, 663828868, 166715034, 73758800, 6399214, 
1122726, 374300, 349366, 191376, 51404, 8914, 297606971, 39680953, 13227015, 
24249509, 1469731, 3061881, 530807, 258661, 18267, 15257 ])
;
G:=$1;
PCGroup(\[ 14, -3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, -3, 3, 59521477, 22320902, 
59522907, 49601681, 9920431, 37206544, 24802488, 33068102, 1378066, 59528215, 
9921035, 3858181, 312558756, 52105052, 40515586, 5789496, 1286900, 857674, 
416894695, 138964917, 6640739, 8827105, 737919, 1225805, 327019, 536519222, 
67237150, 29852586, 2490328, 1932414, 93080, 153574, 225960849, 174522623, 
952625, 1542319, 137447, 68581, 336461212, 166715034, 73758800, 6399214, 
1122726, 374300, 349366, 191376, 51404, 8914, 565453235, 39680953, 13227015, 
24249509, 1469731, 3061881, 530807, 258661, 18267, 15257 ])
;
H:=$1;
Genus (G);
Genus (H);
TGIsIsomorphic (G, H);

**Comment by joshmaglione** [comment] 2019-10-26 12:52
Indeed, this is a bug. Thanks for pointing it out. When I look at the level of the tensors, it seems to work as intended. I'll see what I can find.

```
> s := pCentralTensor(G);
> t := pCentralTensor(H);
> TGIsPseudoIsometric(s, t);
true Maps from U2 x U1 >-> U0 to V2 x V1 >-> V0.
U2 -> V2: 
[2 2 1 2 1 1 2 2 0 0 2 0]
[0 2 0 0 2 0 1 1 2 1 1 0]
[2 0 1 1 2 0 0 2 0 0 0 0]
[2 1 1 0 1 2 1 1 1 0 0 0]
[0 1 2 0 2 2 0 2 0 0 1 1]
[1 2 1 0 1 0 1 0 0 0 2 0]
[2 0 2 0 2 2 1 0 1 1 1 2]
[1 0 1 1 0 1 2 1 2 0 1 0]
[2 2 0 0 2 2 1 0 2 2 2 2]
[1 1 1 0 0 0 1 2 1 1 0 2]
[1 2 2 0 0 0 0 0 2 2 2 2]
[1 0 2 1 1 2 0 2 1 1 1 0]
U1 -> V1: 
[2 2 1 2 1 1 2 2 0 0 2 0]
[0 2 0 0 2 0 1 1 2 1 1 0]
[2 0 1 1 2 0 0 2 0 0 0 0]
[2 1 1 0 1 2 1 1 1 0 0 0]
[0 1 2 0 2 2 0 2 0 0 1 1]
[1 2 1 0 1 0 1 0 0 0 2 0]
[2 0 2 0 2 2 1 0 1 1 1 2]
[1 0 1 1 0 1 2 1 2 0 1 0]
[2 2 0 0 2 2 1 0 2 2 2 2]
[1 1 1 0 0 0 1 2 1 1 0 2]
[1 2 2 0 0 0 0 0 2 2 2 2]
[1 0 2 1 1 2 0 2 1 1 1 0]
U0 -> V0: 
[1 0]
[0 1]
```

**Comment by joshmaglione** [comment] 2019-10-26 13:14
This has been fixed on `dev` and will be on `master` soon. Thanks again!

**Closed by joshmaglione** 2019-10-26 13:14 UTC
